CREATE TABLE `visao_simples` (
  `idLente` int(11) NOT NULL AUTO_INCREMENT,
  `marcaLente` varchar(40) DEFAULT NULL,
  `material` varchar(30) NOT NULL,
  `cor` varchar(15) NOT NULL,
  `tratamento` varchar(20) DEFAULT NULL,
  `descricao` varchar(60) NOT NULL,
  `fotossensivel` varchar(15) DEFAULT NULL,
  `indice` decimal(3,2) NOT NULL,
  `esf_ini` decimal(4,2) NOT NULL,
  `esf_fim` decimal(4,2) NOT NULL,
  `cil_ini` decimal(4,2) NOT NULL,
  `cil_fim` decimal(4,2) NOT NULL,
  `valor` decimal(10,2) DEFAULT NULL,
  `tipo_foto` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`idLente`)
) ENGINE=InnoDB AUTO_INCREMENT=96 DEFAULT CHARSET=latin1;





/*
-- Query: SELECT * FROM lm.visao_simples
LIMIT 0, 100

-- Date: 2018-05-31 23:31
*/
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (1,'Orma Trio','Acrilico','Incolor','EasyClean','Lente Acrilica Incolor Orma Trio EasyClean','Nao',1.49,-6.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (2,'Orma Trio ','Acrilico ','Incolor','EasyClean','Lente Acrilica Incolor Orma Trio EasyClean','Nao ',1.49,0.00,6.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (3,'TFL Trio','Policarbonato','Incolor','EasyClean','Lente Policarbonato Incolor TFL Trio EasyClean','Nao',1.59,-6.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (4,'TFL Trio','Policarbonato','Incolor','EasyClean','Lente Policarbonato Incolor TFL Trio EasyClean','Nao',1.59,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (5,'TFL ','Policarbonato','Incolor','Nao','Lente Policarbonato Incolor TFL','Nao',1.59,-6.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (6,'TFL','Policarbonato','Incolor','Nao','Lente Policarbonato Incolor TFL','Nao',1.59,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (7,'Orma Crizal','Acrilico','Incolor','Crizal Easy','Lente Acrilica Incolor Orma Crizal Easy','Nao',1.49,-6.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (8,'Orma Crizal','Acrilico','Incolor','Crizal Easy','Lente Acrilica Incolor Orma Crizal Easy','Nao',1.49,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (9,'Orma Crizal','Acrilico','Incolor','Crizal Alize Plus','Lente Acrilica Incolor Orma Crizal Alize Plus','Nao',1.49,-5.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (10,'Orma Crizal ','Acrilico','Incolor ','Crizal Alize Plus','Lente Acrilica Incolor Orma Crizal Alize Plus','Nao',1.49,0.00,5.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (11,'Orma Crizal','Acrilico','Incolor','Crizal Forte','Lente Acrilica Incolor Orma Crizal Forte UV','Nao',1.49,-5.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (12,'Orma Crizal ','Acrilico','Incolor ','Crizal Forte','Lente Acrilica Incolor Orma Crizal Forte UV ','Nao',1.49,0.00,5.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (13,'Orma Crizal ','Acrilico','Incolor','Crizal Prevencia','Lente Acrilica Incolor Orma Crizal Prevencia','Nao',1.49,-2.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (14,'Orma Crizal ','Acrilico','Incolor','Crizal Prevencia','Lente Acrilica Incolor Orma Crizal Prevencia','Nao',1.49,0.00,2.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (15,'Orma Optifog','Acrilico','Incolor','Optifog','Lente Acrilica Incolor Orma Optifog','Nao',1.49,-5.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (16,'Orma OPtifog','Acrilico','Incolor ','Optifog','Lente Acrilica Incolor Orma Optifog','Nao',1.49,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (17,'Airwear Crizal','Policarbonato','Incolor','Crizal Easy','Lente  Airwear Incolor Crizal Easy','Nao',1.59,-8.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (18,'Airwear Crizal ','Policarbonato','Incolor','Crizal Easy','Lente  Airwear Incolor Crizal Easy','Nao',1.59,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (19,'Airwear Crizal','Policarbonato','Incolor','Crizal Alize Plus','Lente Airwear Incolor Crizal Alize Plus UV','Nao',1.59,-8.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (20,'Airwear Crizal ','Policarbonato','Incolor','Crizal Alize Plus','Lente Airwear Incolor Crizal Alize Plus UV','Nao',1.59,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (21,'Airwear Crizal','Policarbonato','Incolor','Crizal Forte','Lente Airwear Incolor Crizal Forte','Nao',1.59,-8.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (22,'Airwear Crizal','Policarbonato','Incolor','Crizal Forte','Lente Airwear Incolor Crizal Forte','Nao',1.59,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (23,'Stylis 1.67 Crizal','Acrilico','Incolor','Crizal Alize Plus','Lente Acrilica Stylis 1.67 Crizal Alize Plus','Nao',1.67,-10.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (24,'Stylis 1.67 Crizal','Acrilico','Incolor','Crizal Alize Plus','Lente Acrilica Stylis 1.67 Crizal Alize Pus','Nao',1.67,0.00,6.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (25,'Stylis 1.67','Acrilico','Incolor','Crizal Forte','Lente Acrilica Incolor Stylis 1.67 Crizal Forte','Nao',1.67,-10.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (26,'Stylis 1.67','Acrilico','Incolor','Crizal Forte','Lente Acrilica Incolor Stylis 1.67 Crizal Forte','Nao',1.67,0.00,6.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (27,'Stylis 1.74','Acrilico','Incolor','Crizal Forte','Lente Acrilica Incolor Stylis 1.74 Crizal Forte','Nao',1.74,-12.00,-4.00,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (28,'Orma Acclimates III','Acrilico','Cinza','Nao','Lente Acrilica Orma Acclimates III ','Acclimates',1.49,-4.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (29,'Orma Acclimates III','Acrilico','Cinza','Nao','Lente Acrilica Orma Acclimates III','Acclimates',1.49,0.00,2.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (30,'Orma Transistions','Acrilico','Cinza','Nao','Lente Acrilica Orma Transistions Cinza','Transistions',1.49,-4.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (31,'Orma Transistions','Acrilico','Cinza','Nao','Lente Acrilica Orma Transistions Cinza','Transistions',1.49,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (32,'Orma Transistions','Acrilico','Verde','Nao','Lente Acrilica Orma Transistions Verde','Transistions',1.49,-4.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (33,'Orma Transistions','Acrilico','Verde','Nao','Lente Acrilica Orma Transistions Verde','Transistions',1.49,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (34,'Orma Transistions','Acrilico','Cinza','Crizal Easy','Lente Acrilica Orma Transistions Cinza Crizal Easy','Transistions',1.49,-4.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (35,'Orma Transistions','Acrilico','Cinza','Crizal Easy','Lente Acrilica Orma Transistions Cinza Crizal Easy','Transistions',1.49,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (36,'Orma Transistions','Acrilico','Cinza ','Crizal Forte','Lente Orma Transistions Cinza Crizal Forte','Transistions',1.49,-4.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (37,'Orma Transistions','Acrilico','Cinza ','Crizal Forte','Lente Orma Transistions Cinza Crizal Forte','Transistions',1.49,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (38,'Orma Transistions','Acrilico','Marrom','Crizal Forte','Lente Orma Transistions Marrom Crizal Forte','Transistions',1.49,-4.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (39,'Orma Transistions','Acrilico','Marrom','Crizal Forte','Lente Orma Transistions Marrom Crizal Forte','Transistions',1.49,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (40,'Airwear Transistions','Policarbonato','Cinza','Nao','Lente Airwear Transistions Cinza','Transistions',1.59,-6.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (41,'Airwear Transistions','Policarbonato','Cinza','Nao','Lente Airwear Transistions Cinza','Transistions',1.59,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (42,'Xperio','Acrilico','Cinza','Nao','Lente Acrilica Xperio Solar Cinza Polarizada','Nao',1.49,-6.00,-0.25,0.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (43,'Xperio','Acrilico','Cinza ','Nao','Lente Acrilica Xperio Solar Cinza Polarizada','Nao',1.49,0.00,4.00,0.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (44,'Xperio','Acrilico','Marrom','Nao','Lente Acrilica Xperio Solar Marrom Polarizada','Nao',1.49,-6.00,-0.25,0.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (45,'Xperio','Acrilico','Marrom','Nao','Lente Acrilica Xperio Solar Marrom Polarizada','Nao',1.49,0.00,4.00,0.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (46,'Xperio','Acrilico','Verde ','Nao','Lente Acrilica Xperio Solar Verde Polarizada','Nao',1.49,-6.00,-0.25,0.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (47,'Xperio','Acrilico','Verde','Nao','Lente Acrilica Xperio Solar Verde Polarizada','Nao',1.49,0.00,4.00,0.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (48,'Kodak 1.67','Acrilico','Incolor','NoReflex','Lente Acrilica Incolor Kodak 1.67 NoReflex','Nao',1.67,-12.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (49,'Kodak 1.67 ','Acrilico','Incolor','NoReflex','Lente Acrilica Incolor Kodak 1.67 NoReflex','Nao',1.67,0.00,6.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (50,'Kodak Poly','Policarbonato','Incolor','NoReflex','Lente Policarbonato Incolor Kodak Poly','Nao',1.59,-6.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (51,'Kodak Poly','Policarbonato','Incolor','NoReflex','Lente Policarbonato Incolor Kodak Poly','Nao',1.59,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (52,'Kodak 1.50','Acrilico','Cinza','NoReflex','Lente Acrilica Kodak 1.50 Transistions NoReflex','Transistions',1.50,-4.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (53,'Kodak 1.50','Acrilico','Cinza','NoReflex','Lente Acrilica Kodak 1.50 Transistions NoReflex','Transistions',1.50,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (54,'Kodak 1.50','Acrilico','Incolor','NoReflex','Lente Acrilica Incolor Kodak 1.50 NoReflex','Nao',1.50,-6.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (55,'Kodak 1.50','Acrilico','Incolor','NoReflex','Lente Acrilica Incolor Kodak 1.50 NoReflex','Nao',1.50,0.00,6.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (56,'Kodak 1.53','Acrilico','Incolor','NoReflex','Lente Acrilica Incolor Kodak 1.53 NoReflex','Nao',1.53,-5.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (57,'Kodak 1.53','Acrilico','Incolor','NoReflex','Lente Acrilica Incolor Kodak 1.53 NoReflex','Nao',1.53,0.00,3.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (58,'Ultrax Acqua','Acrilico','Incolor','Acqua','Lente Acrilica Incolor Ultrax Acqua','Nao',1.49,-6.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (59,'Ultrax Acqua','Acrilico','Incolor','Acqua','Lente Acrilica Incolor Ultrax Acqua','Nao',1.49,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (60,'Ultrax CleanExtra','Acrilico','Cinza','CleanExtra','Lente Acrilica Transistions Ultrax CleanExtra','Transistions',1.49,-6.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (61,'Ultrax CleanExtra','Acrilico','Cinza','CleanExtra','Lente Acrilica Transistions Ultrax CleanExtra','Transistions',1.49,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (62,'Ultrax Poly','Policarbonato','Incolor','Acqua','Lente Policarbonato Incolor Ultrax Acqua','Nao',1.59,-6.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (63,'Ultrax Poly','Policarbonato','Incolor','Acqua','Lente Policarbonato Incolor Ultrax Acqua','Nao',1.59,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (64,'Ultrax Trivex','Trivex','Incolor','Acqua','Lente Trivex Incolor Ultrax Acqua','Nao',1.53,-8.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (65,'Ultrax Trivex','Trivex','Incolor','Acqua','Lente Trivex Incolor Ultrax Acqua','Nao',1.53,0.00,3.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (66,'Ultrax Trivex','Trivex','Cinza','CleanExtra','Lente Trivex Transistions Ultrax CleanExtra','Transistions',1.53,-5.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (67,'Ultrax Trivex','Trivex','Cinza','CleanExtra','Lente Trivex Transistions Ultrax CleanExtra','Transistions',1.53,0.00,2.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (68,'ThinHard Poly','Policarbonato','Incolor','Nao','Lente Policarbonato Incolor ThinHard ','Nao',1.59,-6.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (69,'ThinHard Poly','Policarbonato','Incolor','Nao','Lente Policarbonato Incolor ThinHard','Nao',1.59,0.00,4.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (70,'ThinHard Trivex','Trivex','Incolor','Nao','Lente Trivex Incolor ThinHard ','Nao',1.53,-5.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (71,'ThinHard Trivex','Trivex','Incolor','Nao','Lente Trivex Incolor ThinHard ','Nao',1.53,0.00,3.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (72,'ThinHard Trivex','Trivex','Cinza','Nao','Lente Trivex Transistions ThinHard','Transistions',1.53,-5.00,-0.25,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (73,'ThinHard Trivex','Trivex','Cinza','Nao','Lente Trivex Transistions ThinHard ','Transistions',1.53,0.00,2.00,-2.00,0.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (74,'Miolight Trivex','Trivex','Incolor','CleanExtra','Lente Trivex Incolor Miolight','Nao',1.53,-8.00,0.00,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (75,'Miolight Excellence','Acrilico','Incolor','NoRisk','Lente Acrilica Miolight Excellence 1.60 NoRisk','Nao',1.60,-8.00,0.00,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (76,'Miolight 1.67 NoRisk','Acrilico','Incolor','NoRisk','Lente Acrilica Miolight 1.67 NoRisk','Nao',1.67,-10.00,0.00,0.00,3.00,150.00,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (77,'Miolight Long Life 1.74','Acrilico','Incolor','Long Life','Lente Acrilica Miolight 1.74 Long Life','Nao',1.74,-12.00,-4.00,0.00,2.00,NULL,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (88,'Orma','Acrilico','Incolor','Nao','Lente Acrilica Orma -2.00 a -0.25 <> 0.00 a 2.00','Nao',1.49,-2.00,-0.25,0.00,2.00,50.00,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (89,'Orma','Acrilico','Incolor','Nao','Lente Acrilica Orma +0.00 a +2.00 <> -2.00 a 0.00','Nao',1.49,0.00,2.00,-2.00,0.00,50.00,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (90,'Orma','Acrilico','Incolor ','Nao','Lente Acrilica Orma -4.00 a -2.25 <> 0.00 a 2.00','Nao',1.49,-4.00,-2.25,0.00,2.00,65.00,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (91,'Orma','Acrilico','Incolor','Nao','Lente Acrilica Orma +2.25 a +4.00 <> -2.00 a 0.00','Nao',1.49,2.25,4.00,-2.00,0.00,65.00,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (92,'Orma','Acrilico','Incolor','Nao','Lente Acrilica Orma -6.00 a -4.25 <> 0.00 a 2.00','Nao',1.49,-6.00,-4.25,0.00,2.00,80.00,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (93,'Orma','Acrilico','Incolor','Nao','Lente Acrilica  Orma +4.25 a +6.00 <> -2.00 a 0.00','Nao',1.49,4.25,6.00,-2.00,0.00,80.00,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (94,'Off-Ranger','Acrilico','Incolor','Nao','Lente Acrilica Off-Ranger -6.00 a -0.25 <> +2.25 a +4.00','Nao',1.49,-6.00,-0.25,2.25,4.00,120.00,NULL);
INSERT INTO `visao_simples` (`idLente`,`marcaLente`,`material`,`cor`,`tratamento`,`descricao`,`fotossensivel`,`indice`,`esf_ini`,`esf_fim`,`cil_ini`,`cil_fim`,`valor`,`tipo_foto`) VALUES (95,'Off-Ranger','Acrilico','Incolor ','Nao','Lente Acrilica Off-Ranger  +0.00 a 6.00 <> -4.00 a -2.25','Nao',1.49,0.00,6.00,-4.00,-2.25,120.00,NULL);
